#!/bin/bash
# Asher Bond 2011
# rtar remotely archives a local directory
# https://github.com/AsherBond/Continuous-Integrator/
# LICENSE: AGPL version 3

USAGE='rtar </directory/to/archive> <destination-user> <destination.host> <port> <outfile.tar> [privatekey.pem]'

dir=$1
user=$2
desthost=$3
port=$4
outfile=$5

if [ -z $1$2$3$4$5 ]; then
	echo "$USAGE"
	exit
fi

if [ ! -z $6 ]; then
	privatekey="-i $6"
fi

(cd $dir ; tar cpf - .) |ssh $privatekey -l $user $desthost $port dd of=$outfile obs=1024
